apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pv-claim
  namespace: unifi-controller
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
