apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
  namespace: unifi-controller
spec:
  ports:
  - name: web-management
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: unifi-controller
  type: LoadBalancer
