apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller-udp
  namespace: unifi-controller
spec:
  ports:
  - name: device-discovery
    port: 10001
    protocol: UDP
    targetPort: 10001
  - name: controller-discovery
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: stun
    port: 3478
    protocol: UDP
    targetPort: 3478
  selector:
    app: unifi-controller
  type: LoadBalancer
