apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
  namespace: unifi-controller
spec:
  ports:
  - name: web-management
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: device-inform
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: guest-portal
    port: 8980
    protocol: TCP
    targetPort: 8880
  - name: throughput-speedtest
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: unifi-controller
  type: LoadBalancer
